export const HISTORY_PARAGRAPHS = [
  "Nuestra iglesia tiene sus inicios en el año 1956, cuando un pequeño grupo de mujeres y niños se reunía en un garaje con un propósito claro: orar y pedir al Señor que levantará un pastor.",
  "Dios respondió a ese clamor llamando al ministerio pastoral a José Ignacio Fuentes, junto a su esposa Graciela Donoso. Ambos decidieron obedecer el llamado de Dios, apartándose de la congregación en la que se encontraban, al no compartir plenamente la enseñanza sobre el Espíritu Santo. En ese tiempo, el Señor comenzó a hablarles a través de sueños, guiándolos hacia un propósito mayor.",
  "En 1961 ocurre un hecho clave en nuestra historia. Desde Brasil llega a Chile el Obispo L.A. Parent, quien, sin tener inicialmente a Chile en sus planes, es dirigido por Dios. En su camino se encuentra con el pastor misionero Juan Alvear, quien le conecta con el pastor Fuentes.",
  "El Obispo Parent recordaba una visión que Dios le había dado años atrás, donde veía al mundo en llamas, excepto dos lugares: Michigan y Chile. Convencido de que Chile era parte del propósito de Dios, viaja y comparte el mensaje que marcaría el inicio de esta obra: \"Un Señor, una fe, un bautismo, un Dios y Padre de todos...\" (Efesios 4:5-6).",
  "A partir de ese momento, comienzan los primeros bautismos en el nombre de Jesús, realizados en las Termas de Colina, y se establece la primera congregación en el hogar del pastor Fuentes, ubicado en Tacora 2573.",
  "Con el paso del tiempo, la iglesia comienza a crecer de manera sostenida. Muchas vidas son transformadas y llenas del Espíritu Santo. La predicación se extiende a través de distintos medios, incluyendo la radio, donde el pastor Fuentes fue pionero en anunciar este mensaje, impactando a numerosos oyentes.",
  "La obra no solo se expandió a lo largo de Chile, sino que también cruzó fronteras, estableciendo iglesias en Argentina y Perú, confirmando que era Dios quien abría puertas que nadie podía cerrar.",
  "A lo largo de los años, la iglesia continuó creciendo tanto espiritual como físicamente. En 1973 se amplía el espacio original, en 1982 se extiende hacia el sector de Barón de Juras Reales, y en 1985 se construye un segundo piso destinado a la enseñanza de niños.",
  "En el año 2014 comienza la construcción de nuestro actual templo, el cual fue inaugurado en 2016, representando un nuevo tiempo de consolidación y desarrollo para la iglesia.",
  "El año 2021 marca un momento significativo en nuestra historia, al partir a la presencia del Señor nuestro Apóstol José Ignacio Fuentes y su esposa Graciela Donoso, quienes fueron los instrumentos que Dios utilizó para dar inicio a esta obra en Chile.",
  "Hoy, continuamos avanzando con la misma visión: predicar el evangelio de Jesucristo, alcanzar vidas y extender el Reino de Dios, confiando en que la puerta que Él abrió permanece abierta hasta el día de hoy.",
]
